[project]
name = "rp-flask-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "connexion[flask,swagger-ui,uvicorn]>=3.2.0",
    "flask-marshmallow[sqlalchemy]>=1.3.0",
    "flask>=3.1.1",
]
